name: Deploy MkDocs Documentation


on:
  release:
    types: [published]  # Only run when a release is published
  workflow_dispatch:  
permissions:
  contents: write  # required to deploy to GitHub Pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: doc-deploy  # <-- Environment name

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
 
      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          pip install .[dev]

      - name: 🛠️ Build documentation
        run: |
          mkdocs build

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
